spring:
  application:
    name: coffeemachine
  datasource:
    url: jdbc:mysql://localhost:3306/coffeesmachine?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
        access: unrestricted
        
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}
    client:
        fetch-registry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eurekacoffee
info:
    app:
        name: "Coffees"
        description: "Coffee Machine"
        version: "5.0"
            
    
greeting:
  name: Dakota
  coffee: ${greeting.name} is drinking coffee
  
account:
  message: "welcome"
  details:
      name: "bob"
      email: "{cipher}de8e35a43e9f7886f07ac63f092db1afccb648029acf99e77e3b44db124f2f59806b8b2ab7c10c0d37622584775a9b52"
  phone:
      - 0233566666
      - 0233366666
build:
  version: "2.0"