spring:
  application:
    name: coffeemachine
  datasource:
    url: jdbc:mysql://localhost:3306/coffeesmachine?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: '*'
greeting:
  name: Dakota
  coffee: ${greeting.name} is drinking coffee
  
account:
  message: "welcome"
  details:
      name: "bob"
      email: "gshqgdj@qsdhqsfd"
  phone:
      - 0233566666
      - 0233366666
build:
  version: "2.0"